// tests/playwright/vendor.mjs — local stand-ins for the CDN URLs the pages import (design 03 §8.6).
// Cloud runner only; never deployed, never loaded by a page on the user's machine.
//
// `npm pack` fetches the exact package tarballs into the gitignored .vendor/ (no install, no
// package.json, no bundler); they are unpacked with `tar`, and ESM shims are written over the
// UMD/CJS development builds so the import-map URLs can be served by page.route():
//
//   https://esm.sh/react@18.3.1                       → shims/react.js        (umd/react.development.js)
//   https://esm.sh/react@18.3.1/jsx-runtime           → shims/jsx-runtime.js  (cjs/react-jsx-runtime.development.js)
//   https://esm.sh/react-dom@18.3.1                   → shims/react-dom.js    (umd/react-dom.development.js)
//   https://esm.sh/react-dom@18.3.1/client            → shims/react-dom-client.js (re-uses the react-dom shim)
//   https://esm.sh/lucide-react@0.454.0?external=react → shims/lucide-react.js (dist/umd/lucide-react.js)
//   https://cdn.jsdelivr.net/npm/@babel/standalone@7.26.4/babel.min.js → @babel/standalone/babel.min.js
//
// Every shim imports React through the page's import map (bare "react"), so the page holds one
// React and one ReactDOM instance. pdfjs-dist is packed for ctx.pdfText (Node side only).
//
// Usage: `node vendor.mjs` (idempotent), or `import { ensureVendor } from "./vendor.mjs"`.
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync, rmSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import vm from "node:vm";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const VENDOR_DIR = path.join(HERE, ".vendor");
const TGZ_DIR = path.join(VENDOR_DIR, "tgz");
const PKG_DIR = path.join(VENDOR_DIR, "pkg");
const SHIM_DIR = path.join(VENDOR_DIR, "shims");
const SHIM_VERSION = 2; // bump to regenerate the shims

export const PACKAGES = [
  { name: "react", version: "18.3.1" },
  { name: "react-dom", version: "18.3.1" },
  { name: "scheduler", version: "0.23.2" },
  { name: "lucide-react", version: "0.454.0" },
  { name: "@babel/standalone", version: "7.26.4" },
  { name: "pdfjs-dist", version: "4.10.38" },
];

const pkgPath = (name, ...rest) => path.join(PKG_DIR, ...name.split("/"), ...rest);

function sh(cmd, args, opts = {}) {
  return execFileSync(cmd, args, { stdio: ["ignore", "pipe", "pipe"], encoding: "utf8", ...opts });
}

function unpack(pkg, log) {
  const dest = pkgPath(pkg.name);
  const marker = path.join(dest, "package.json");
  if (existsSync(marker)) {
    const v = JSON.parse(readFileSync(marker, "utf8")).version;
    if (v === pkg.version) return dest;
    rmSync(dest, { recursive: true, force: true });
  }
  mkdirSync(TGZ_DIR, { recursive: true });
  const spec = `${pkg.name}@${pkg.version}`;
  log(`npm pack ${spec}`);
  const out = sh("npm", ["pack", spec, "--silent", "--pack-destination", TGZ_DIR]).trim().split("\n").pop().trim();
  const tgz = path.join(TGZ_DIR, out);
  if (!existsSync(tgz)) throw new Error(`npm pack ${spec} produced no tarball (${out})`);
  mkdirSync(dest, { recursive: true });
  sh("tar", ["-xzf", tgz, "-C", dest, "--strip-components=1"]);
  return dest;
}

/** Evaluate a CJS/UMD body in Node with the given `require`, returning module.exports. */
function evaluate(source, filename, requireFn) {
  const module = { exports: {} };
  const fn = vm.runInThisContext(`(function (module, exports, require, define, process) {\n${source}\n})`, { filename });
  fn.call(globalThis, module, module.exports, requireFn, undefined, { env: { NODE_ENV: "development" } });
  return module.exports;
}

const IDENT = /^[A-Za-z_$][\w$]*$/;
const RESERVED = new Set(["default", "arguments", "eval", "await", "yield", "let", "static", "enum", "implements",
  "package", "protected", "interface", "private", "public"]);

function exportNames(obj) {
  return Object.keys(obj).filter((k) => IDENT.test(k) && !RESERVED.has(k)).sort();
}

/** ESM text around a CJS/UMD body. `imports` binds names for the fake require. */
function shim({ banner, imports, requireMap, source, names }) {
  const req = Object.entries(requireMap)
    .map(([spec, expr]) => `  if (n === ${JSON.stringify(spec)}) return ${expr};`).join("\n");
  return `// ${banner}\n// Generated by tests/playwright/vendor.mjs; local test runner only.\n${imports}\n` +
    `const __module = { exports: {} };\n` +
    `const __require = (n) => {\n${req}\n  throw new Error("vendor shim: unexpected require(" + n + ")");\n};\n` +
    `(function (module, exports, require, define, process) {\n${source}\n}).call(globalThis, __module, __module.exports, __require, undefined, { env: { NODE_ENV: "development" } });\n` +
    `const __e = __module.exports;\nexport default __e;\n` +
    (names.length ? `export const { ${names.join(", ")} } = __e;\n` : "");
}

function buildShims(log) {
  mkdirSync(SHIM_DIR, { recursive: true });
  const stamp = path.join(SHIM_DIR, ".version");
  if (existsSync(stamp) && readFileSync(stamp, "utf8").trim() === String(SHIM_VERSION)) return;
  log("writing ESM shims");

  const reactSrc = readFileSync(pkgPath("react", "umd", "react.development.js"), "utf8");
  const React = evaluate(reactSrc, "react.development.js", () => { throw new Error("react requires nothing"); });
  writeFileSync(path.join(SHIM_DIR, "react.js"), shim({
    banner: "react@18.3.1 umd/react.development.js as ESM", imports: "", requireMap: {}, source: reactSrc, names: exportNames(React),
  }));

  const jsxSrc = readFileSync(pkgPath("react", "cjs", "react-jsx-runtime.development.js"), "utf8");
  const Jsx = evaluate(jsxSrc, "react-jsx-runtime.development.js", (n) => { if (n === "react") return React; throw new Error(n); });
  writeFileSync(path.join(SHIM_DIR, "jsx-runtime.js"), shim({
    banner: "react@18.3.1 cjs/react-jsx-runtime.development.js as ESM", imports: 'import __React from "react";',
    requireMap: { react: "__React" }, source: jsxSrc, names: exportNames(Jsx),
  }));

  const domSrc = readFileSync(pkgPath("react-dom", "umd", "react-dom.development.js"), "utf8");
  const ReactDOM = evaluate(domSrc, "react-dom.development.js", (n) => { if (n === "react") return React; throw new Error(n); });
  writeFileSync(path.join(SHIM_DIR, "react-dom.js"), shim({
    banner: "react-dom@18.3.1 umd/react-dom.development.js as ESM", imports: 'import __React from "react";',
    requireMap: { react: "__React" }, source: domSrc, names: exportNames(ReactDOM),
  }));

  // react-dom/client.js does exactly this in the npm package: it marks the call as coming
  // from the client entry point, so React does not warn about importing createRoot from react-dom.
  writeFileSync(path.join(SHIM_DIR, "react-dom-client.js"),
    `// react-dom@18.3.1/client as ESM over the react-dom shim (mirrors the package's client.js).\n` +
    `// Generated by tests/playwright/vendor.mjs; local test runner only.\n` +
    `import ReactDOM from "react-dom";\n` +
    `const i = ReactDOM.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;\n` +
    `export function createRoot(c, o) { i.usingClientEntryPoint = true; try { return ReactDOM.createRoot(c, o); } finally { i.usingClientEntryPoint = false; } }\n` +
    `export function hydrateRoot(c, h, o) { i.usingClientEntryPoint = true; try { return ReactDOM.hydrateRoot(c, h, o); } finally { i.usingClientEntryPoint = false; } }\n` +
    `export default { createRoot, hydrateRoot };\n`);

  const lucideSrc = readFileSync(pkgPath("lucide-react", "dist", "umd", "lucide-react.js"), "utf8");
  const Lucide = evaluate(lucideSrc, "lucide-react.js", (n) => { if (n === "react") return React; throw new Error(n); });
  writeFileSync(path.join(SHIM_DIR, "lucide-react.js"), shim({
    banner: "lucide-react@0.454.0 dist/umd/lucide-react.js as ESM", imports: 'import __React from "react";',
    requireMap: { react: "__React" }, source: lucideSrc, names: exportNames(Lucide),
  }));

  writeFileSync(stamp, `${SHIM_VERSION}\n`);
}

/**
 * Pack, unpack and shim everything once. Returns the route table and helper paths.
 * @returns {{dir: string, routes: Record<string, {file: string, contentType: string}>, pdfjs: string, pdfjsWorker: string, versions: Record<string,string>}}
 */
export function ensureVendor({ log = (m) => console.error(`[vendor] ${m}`) } = {}) {
  mkdirSync(PKG_DIR, { recursive: true });
  for (const pkg of PACKAGES) unpack(pkg, log);
  buildShims(log);
  const js = "text/javascript; charset=utf-8";
  const routes = {
    "https://esm.sh/react@18.3.1": { file: path.join(SHIM_DIR, "react.js"), contentType: js },
    "https://esm.sh/react@18.3.1/jsx-runtime": { file: path.join(SHIM_DIR, "jsx-runtime.js"), contentType: js },
    "https://esm.sh/react-dom@18.3.1": { file: path.join(SHIM_DIR, "react-dom.js"), contentType: js },
    "https://esm.sh/react-dom@18.3.1/client": { file: path.join(SHIM_DIR, "react-dom-client.js"), contentType: js },
    "https://esm.sh/lucide-react@0.454.0?external=react": { file: path.join(SHIM_DIR, "lucide-react.js"), contentType: js },
    "https://cdn.jsdelivr.net/npm/@babel/standalone@7.26.4/babel.min.js": { file: pkgPath("@babel/standalone", "babel.min.js"), contentType: js },
  };
  for (const [url, r] of Object.entries(routes)) if (!existsSync(r.file)) throw new Error(`vendor: missing ${r.file} for ${url}`);
  return {
    dir: VENDOR_DIR,
    routes,
    pdfjs: pkgPath("pdfjs-dist", "legacy", "build", "pdf.mjs"),
    pdfjsWorker: pkgPath("pdfjs-dist", "legacy", "build", "pdf.worker.mjs"),
    versions: Object.fromEntries(PACKAGES.map((p) => [p.name, p.version])),
  };
}

let pdfjsPromise = null;

/**
 * Text items of every page of a PDF, for the `print` spec (§8.0 ctx.pdfText).
 * Coordinates are in PDF points with the origin at the TOP-left of the page: x, y is the
 * top-left corner of the item's box, w and h its width and height.
 * @returns {Promise<Array<{page: number, width: number, height: number, items: Array<{str, x, y, w, h}>}>>}
 */
export async function pdfText(buffer, vendor = ensureVendor({ log: () => {} })) {
  if (!pdfjsPromise) {
    pdfjsPromise = import(pathToFileURL(vendor.pdfjs).href).then((pdfjs) => {
      pdfjs.GlobalWorkerOptions.workerSrc = pathToFileURL(vendor.pdfjsWorker).href;
      return pdfjs;
    });
  }
  const pdfjs = await pdfjsPromise;
  const data = buffer instanceof Uint8Array ? new Uint8Array(buffer) : new Uint8Array(buffer);
  const doc = await pdfjs.getDocument({ data, useSystemFonts: false, isEvalSupported: false, verbosity: 0 }).promise;
  const pages = [];
  for (let p = 1; p <= doc.numPages; p++) {
    const page = await doc.getPage(p);
    const vp = page.getViewport({ scale: 1 });
    const content = await page.getTextContent();
    const items = [];
    for (const it of content.items) {
      if (typeof it.str !== "string" || !it.str.trim()) continue;
      const [, , , , e, f] = it.transform;
      const h = it.height || Math.abs(it.transform[3]) || 0;
      items.push({ str: it.str, x: e, y: vp.height - f - h, w: it.width, h });
    }
    pages.push({ page: p, width: vp.width, height: vp.height, items });
  }
  await doc.destroy();
  return pages;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const v = ensureVendor();
  const listing = readdirSync(SHIM_DIR).filter((f) => f.endsWith(".js"));
  console.log(JSON.stringify({ dir: v.dir, versions: v.versions, shims: listing, routes: Object.keys(v.routes) }, null, 2));
}
